#!/Users/jrignell/dev/DSLR/.env/bin/python3

from src import check_args, handle_open, NUMBER_TYPES
from classes import Analysis
import pandas as pd

def main():
    analysis = Analysis()
    print(analysis._df.describe())
    analysis.count_rows_sum()
    analysis.mean()
    analysis.std()
    analysis.min()
    analysis.count_quartiles()
    analysis.max()
    print(pd.DataFrame(analysis._summary))

if __name__ == '__main__':
    main()